In [ ]:
import numpy as np
import random

class QLearning:
    def __init__(self, num_states, num_actions, learning_rate=0.1, discount_factor=0.9, exploration_rate=0.1):
        """
        Initialize Q-learning algorithm
        
        Parameters:
        - num_states: Number of states in the environment
        - num_actions: Number of possible actions
        - learning_rate: Alpha, how much we update our estimate each step
        - discount_factor: Gamma, how much we value future rewards
        - exploration_rate: Epsilon, probability of random exploration
        """
        self.q_table = np.zeros((num_states, num_actions))
        self.learning_rate = learning_rate
        self.discount_factor = discount_factor
        self.exploration_rate = exploration_rate
    
    def get_action(self, state):
        """
        Select an action using epsilon-greedy policy
        """
        if random.random() < self.exploration_rate:
            # Explore: random action
            return random.randint(0, self.q_table.shape[1] - 1)
        else:
            # Exploit: best known action
            return np.argmax(self.q_table[state])
    
    def update_q_value(self, state, action, reward, next_state):
        """
        Update Q-value using the Bellman equation
        Q(s,a) = Q(s,a) + α * (r + γ * max_a' Q(s',a') - Q(s,a))
        """
        best_next_action = np.argmax(self.q_table[next_state])
        td_target = reward + self.discount_factor * self.q_table[next_state][best_next_action]
        td_error = td_target - self.q_table[state][action]
        self.q_table[state][action] += self.learning_rate * td_error

if __name__ == "__main__":
    NUM_STATES = 16  # 4x4 grid
    NUM_ACTIONS = 4  # up, down, left, right
    
    q_agent = QLearning(NUM_STATES, NUM_ACTIONS)
    
    for episode in range(1000):
        state = 0  # start state
        done = False
        
        while not done:
            # Get action
            action = q_agent.get_action(state)
            
            # Simulate environment (in a real scenario, this would come from the environment)
            # For this example, let's say:
            # - Action 0=up, 1=right, 2=down, 3=left
            # - State is represented as 0-15 (4x4 grid)
            # - Reaching state 15 is the goal with reward +10
            # - Hitting walls keeps in same state with -1 reward
            
            # Simple environment dynamics
            if state == 15:  # goal state
                reward = 0
                done = True
                next_state = state
            else:
                if action == 0:  # up
                    next_state = state - 4 if state >= 4 else state
                elif action == 1:  # right
                    next_state = state + 1 if (state + 1) % 4 != 0 else state
                elif action == 2:  # down
                    next_state = state + 4 if state < 12 else state
                else:  # left
                    next_state = state - 1 if state % 4 != 0 else state
                
                reward = 10 if next_state == 15 else -0.1  # small penalty for each step
            
            # Update Q-value
            q_agent.update_q_value(state, action, reward, next_state)
            state = next_state
    
    # Print learned Q-table
    print("Learned Q-table:")
    print(q_agent.q_table)
    

Learned Q-table:
[[ 4.67533303e+00  4.29228833e+00  5.49539000e+00  4.58529499e+00]
 [ 2.47983150e-01  1.35288005e-03  5.92236733e+00 -6.77918488e-02]
 [-3.93238000e-02 -3.61489009e-02  1.70303288e+00  4.80690858e-01]
 [-4.57390000e-02 -2.97010000e-02 -2.88100000e-02  1.48363951e-01]
 [ 4.60093369e+00  5.58326330e+00  6.21710000e+00  5.05158574e+00]
 [ 8.72202184e-01  1.71502883e+00  7.01673654e+00  1.47300862e+00]
 [ 2.13741706e-01  6.23153636e-01  7.73785021e+00 -2.07910000e-02]
 [-2.97010000e-02  7.20810422e-01  8.59129432e+00  9.85348164e-01]
 [ 5.22316247e+00  7.01900000e+00  3.25874087e+00  5.11374720e+00]
 [ 5.57876186e+00  7.91000000e+00  3.79603638e+00  5.87889432e+00]
 [ 6.04890140e+00  8.90000000e+00  6.42814031e+00  6.78282606e+00]
 [ 6.72081050e+00  8.25808822e+00  1.00000000e+01  7.57443207e+00]
 [ 5.49438140e+00 -2.88100000e-02  5.93994777e-01 -2.97010000e-02]
 [-1.40805550e-02  6.11094040e+00 -1.00000000e-02  4.32006317e-01]
 [ 7.88087761e+00  3.43900000e+00  6.61031693